### ISSUE TITLE
API authentication Failure

### ISSUE THREAD

**Issue by ZerkerEOD** [sm00v/Dehashed#1]
Seems to have an issue where it will not authenticate with Dehashed with my email and api key but h8mail doesn't have an issue.

I have tried passing both as args, and hard coded into the code. Mind looking into it?

**Comment by sm00v** [comment]
I'm obviously a terrible maintainer lol. Did you ever figure this out?

**Comment by ZerkerEOD** [comment]
Kinda, you have to pay for both their subscription and API credits. Which I won't use the service enough to pay for out of my pocket. 

And on top of that none of me emails/help tickets ever got a reply either as I requested LEO account for my company due to local government pentests that we do and never heard back about that either. The Dehashed service may be great but there support is absolutely trash.

**Comment by ChillVibesMushroom** [comment]
So all I need to do is put my api key in the api parameter and put my username and then run your python script and gather credentials on emails

**Comment by CodingApfel** [comment]
Is the Dehashed Service down ? For me it's not working.

**Comment by ZerkerEOD** [comment]
> Is the Dehashed Service down ? For me it's not working. I Always get this Error: [-] API Authentication Failure.

It hasn't been down but I think the owner of Dehashed is in jail. He never responds to emails and I haven't seen any new breach data in a couple years. Seems to just be on autopilot

**Comment by ChillVibesMushroom** [comment]
> > Is the Dehashed Service down ? For me it's not working. I Always get this Error: [-] API Authentication Failure.
> 
> It hasn't been down but I think the owner of Dehashed is in jail. He never responds to emails and I haven't seen any new breach data in a couple years. Seems to just be on autopilot

How did you figure out he's in jail I wonder who's maintaining the site did you try to do an nslookup and get the email of the owner of the site or someone else who may have answers :3

**Comment by ZerkerEOD** [comment]
> > > Is the Dehashed Service down ? For me it's not working. I Always get this Error: [-] API Authentication Failure.
> > 
> > 
> > It hasn't been down but I think the owner of Dehashed is in jail. He never responds to emails and I haven't seen any new breach data in a couple years. Seems to just be on autopilot
> 
> How did you figure out he's in jail I wonder who's maintaining the site did you try to do an nslookup and get the email of the owner of the site or someone else who may have answers :3

No I'm not worried enough to try and hunt the guy down. Just a theory as I haven't seen it heard anything from them.
